### ISSUE TITLE
Implement GPT-4 API

### ISSUE THREAD

**Issue by kramerc3** [brendanpayne/protifyapp#23]
### Story Description:
This will serve as the initial integration of the AI model with Protify. 

#### Acceptance Criteria:
1. API added to build file

2. Test calls can be executed

#### Additional Information:
- https://platform.openai.com/playground
- https://openai.com/gpt-4

#### Tasks:

- Connect API using an external branch to master
- Connect payment method to openai playground
- Store API key in gitignore temporarily
- Create basic logic for testing API calls

**Comment by uc-mcreyntm** [comment]
We have started testing with gpt-3.5 json output. We were able to feed it weather data and out it output time's that I user should not do outdoor events.

**Comment by uc-mcreyntm** [comment]
Implemented API calls into the code. Successfully getting structured json output in a parseable format.

**Comment by uc-mcreyntm** [comment]
Working on compressing data into a reasonable amount to allow for more efficient  queries. For example, I am getting a list of the user's free time throughout the day, in chunks, so the AI can determine which windows it's allowed to schedule events in.

I also am working on a function to determine whether certain events are chained. This one is kinda hard to explain and it kinda abstract. 

The best way I can explain this is with an example. Tom has "Work" on his calendar, ending at 430 PM. His next event is "Gym" at 5PM. It takes Tom 25 minutes to get to the gym from work. Since the time it takes him to get to the gym from work essentially blocks out all of his free time from 430pm to 500pm, this would be considered a chained event. His calendar will be blocked from the start time of work (8am) to the end time of gym (630pm). Now the AI won't recommend an event in between 430pm and 5pm because Tom most likely wouldn't be able to partake in that event while hes driving.

**Comment by uc-mcreyntm** [comment]
Made improvements to the logic behind isChainedEvent function. It can now succesfully determine all of the free time a user has in a given day using the isChainedEvent function in conjunction with the getFreeTime function.

I tested by adding events for the day as follows:
Work 8am-430pm
Gym 445pm-545pm
standup 7pm-9pm
groceries 910pm-945pm
study 950pm-1050pm

The users "active hours" are listed as 7am through 10pm.

Here are results

![image](https://github.com/brendanpayne/protifyapp/assets/89491042/3eda3863-5982-428e-9f93-acd9ecc2c4ee)


As you can see, the Gym, groceries, and study are seen as "chained events", so it only displays the proper free time gaps.

**Comment by uc-mcreyntm** [comment]
First successful api call reorganizing events based off of travel times.

The top is what events were given to the api. Along with events, a matrix of travel times (every possible combination of travel between events and home) was fed to the AI so it could intelligently figure out the best options.

The bottom was the response... success.



![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/4df70775-d657-422b-8d32-03b349715bbf)

**Comment by uc-mcreyntm** [comment]
Created functions that actually take the response from open AI, then modify those entryies in firestore.


Need to work out some kinks:
Right now, I am searching for events by name. If the case doesn't exactly match, it won't pull any results.
If it pulls more than one event with the same name, it will fail.

I need to implement some kind of unique identifier to these events as they're piped into the api, so we're able to distinguish them on their way out.

**Comment by uc-mcreyntm** [comment]
Added new fields to FirestoreEvent to make querying easier and a boolean for isOutside. That will be used for the upcoming feature of not scheduling events while it's raining. 

I found that the prompt is not returning results as I thought. It's not making any sugguestions to schedules that could be optimized, which is concerning. I'll have to look into other prompts, as possibly other options (vertex AI was able to give me pretty good responses). If this problem continues, I might need help from the team on this or possibly use another API. I don't think the implementation of another API would be too terrible, maybe about 3-5 hours of work to change up the API call and json object response class.

**Comment by uc-mcreyntm** [comment]
A lot of cleanup today. I moved a lot of the logic that I was using purely for testing into classes so code is more readable and modifyable.

I was able to get nice responses after I switched to GPT-4 for one test. I will probably keep piloting everything with GPT 3.5, and use GPT 4.0 for the presentation and expo. No matter if you saved hours of driving time by changing events around, GPT 3.5 just wouldn't sugguest anything else.

Created a new AI call function that will only be called if there is any rain predicited for the day. If so, then it will send a different response to the AI in hopes that both weather and driving data can be used. I haven't tested this yet, but it's looking pretty promising because the prompt is very straight forward.

**Comment by uc-mcreyntm** [comment]
Started working with unit testing again. I'm having good success with it.

I figured since we're going to need them eventually, I should just implement them now. This will also help with future testing with the API, since all of data from the API calls is saved locally as json, I don't need to run hundreds of API calls that are requesting the same data.

Side note: These technically aren't unit tests. They are instrumentation tests. Since the entirety of our backend relies on external services (APIs & Databases) to get its information, and unit tests don't allow async methods, this was the only route to go.
